package scoring

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// TestParityWithPython loads parity_fixtures.json (generated by
// backlogist/scripts/dump_scoring_fixtures.py) and asserts Go computation
// matches Python within ±0.05 on every scoring field.
//
// If drift is detected: (a) run
// `.venv-audit/bin/python -m backlogist.scripts.dump_scoring_fixtures`
// to regenerate; (b) if fixtures regenerate to different values, Python
// scoring semantics changed and this Go port must be updated to match.
func TestParityWithPython(t *testing.T) {
	fixturePath := filepath.Join("parity_fixtures.json")
	raw, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}

	var fixtures []struct {
		Name        string   `json:"name"`
		ReleaseDate string   `json:"release_date"`
		Tasks       []Task   `json:"tasks"`
		Expected    []Result `json:"expected"`
	}
	if err := json.Unmarshal(raw, &fixtures); err != nil {
		t.Fatalf("parse fixtures: %v", err)
	}

	tolerance := 0.05

	for _, fx := range fixtures {
		fx := fx
		t.Run(fx.Name, func(t *testing.T) {
			got := RecalculateAll(fx.Tasks, fx.ReleaseDate, NoCapabilityStatus)
			if len(got) != len(fx.Expected) {
				t.Fatalf("result count mismatch: got %d, want %d", len(got), len(fx.Expected))
			}
			byID := map[int]Result{}
			for _, r := range got {
				byID[r.ID] = r
			}
			for _, exp := range fx.Expected {
				g, ok := byID[exp.ID]
				if !ok {
					t.Errorf("task #%d missing in results", exp.ID)
					continue
				}
				checkFloat(t, exp.ID, "effective", g.Effective, exp.Effective, tolerance)
				checkFloat(t, exp.ID, "potential", g.Potential, exp.Potential, tolerance)
				checkFloat(t, exp.ID, "base", g.Base, exp.Base, tolerance)
				checkFloat(t, exp.ID, "impact_points", g.ImpactPoints, exp.ImpactPoints, tolerance)
				checkFloat(t, exp.ID, "subjective", g.Subjective, exp.Subjective, tolerance)
				checkFloat(t, exp.ID, "blocker_value", g.BlockerValue, exp.BlockerValue, tolerance)
				checkInt(t, exp.ID, "release_bonus", g.ReleaseBonus, exp.ReleaseBonus)
				checkInt(t, exp.ID, "broken_bonus", g.BrokenBonus, exp.BrokenBonus)
				checkInt(t, exp.ID, "consumers_bonus", g.ConsumersBonus, exp.ConsumersBonus)
				checkInt(t, exp.ID, "unblocks", g.Unblocks, exp.Unblocks)
				checkBool(t, exp.ID, "is_blocked", g.IsBlocked, exp.IsBlocked)
				checkBool(t, exp.ID, "has_spec", g.HasSpec, exp.HasSpec)
				checkString(t, exp.ID, "type", g.Type, exp.Type)
			}
		})
	}
}

func checkFloat(t *testing.T, id int, field string, got, want, tol float64) {
	t.Helper()
	if math.Abs(got-want) > tol {
		t.Errorf("task #%d %s: got %v, want %v (tol %v)", id, field, got, want, tol)
	}
}

func checkInt(t *testing.T, id int, field string, got, want int) {
	t.Helper()
	if got != want {
		t.Errorf("task #%d %s: got %d, want %d", id, field, got, want)
	}
}

func checkBool(t *testing.T, id int, field string, got, want bool) {
	t.Helper()
	if got != want {
		t.Errorf("task #%d %s: got %v, want %v", id, field, got, want)
	}
}

func checkString(t *testing.T, id int, field, got, want string) {
	t.Helper()
	if got != want {
		t.Errorf("task #%d %s: got %q, want %q", id, field, got, want)
	}
}

// TestRecalculateUnblocked_RemovesClosedIDAndFlags verifies the entry-point
// used by AdvanceTask on DONE: BlockedBy is scrubbed in-place and unblocked
// IDs are returned.
func TestRecalculateUnblocked_RemovesClosedIDAndFlags(t *testing.T) {
	tasks := []Task{
		{ID: 100, Title: "parent already DONE", Owner: "samvel", Mode: "Code", Status: "DONE"},
		{ID: 101, Title: "child was blocked", Owner: "samvel", Mode: "Code", Status: "READY",
			BlockedBy: []int{100}},
		{ID: 102, Title: "unrelated free", Owner: "samvel", Mode: "Code", Status: "READY"},
	}

	unblocked := RecalculateUnblocked(100, tasks, "2026-07-25", NoCapabilityStatus)

	// #101 became unblocked.
	found := false
	for _, id := range unblocked {
		if id == 101 {
			found = true
		}
	}
	if !found {
		t.Errorf("expected #101 in unblocked list, got %v", unblocked)
	}
	if len(tasks[1].BlockedBy) != 0 {
		t.Errorf("expected #101 BlockedBy=[], got %v", tasks[1].BlockedBy)
	}
	if tasks[1].EffectiveScore <= 0.0 {
		t.Errorf("expected #101 EffectiveScore > 0 after unblock, got %v", tasks[1].EffectiveScore)
	}
	// Unrelated task untouched.
	if len(tasks[2].BlockedBy) != 0 {
		t.Errorf("expected #102 BlockedBy=[], got %v", tasks[2].BlockedBy)
	}
}
